(function (root) {
  'use strict';
  const locales = Object.freeze({
    de: Object.freeze({
      tagline:'Die Stadt, die zu Ihnen spricht',start:'Paris entdecken',included_note:'5 vielfältige Geschichten kostenlos. Ein Kauf öffnet alle 44 Orte. Ohne Werbung, Konto oder Analyse. Die Kamera bleibt Ihre Wahl.',privacy_summary:'Datenschutz',privacy_splash:'Standort und Ausrichtung werden nicht gespeichert. Kamerabilder werden weder aufgezeichnet noch übertragen.',creation:'Eine Kreation von',directions_approx:'Richtungen sind Näherungswerte',
      around:'🔭 Umgebung',map:'🗺️ Karte',list:'📜 Liste',location_loading:'Standort wird ermittelt…',precise_location:'Genauer Standort',approx_location:'Ungefährer Standort',gps_denied:'GPS abgelehnt · simuliert',gps_unavailable:'GPS nicht verfügbar · simuliert',explore_mode:'Entdeckungsmodus',explore_text:'Aktivieren Sie die Kamera für AR. Die Richtungspfeile bleiben immer verfügbar.',enable_camera:'Kamera aktivieren',without_camera:'Ohne Kamera fortfahren',camera_privacy:'🔒 Das Kamerabild verlässt Ihr Telefon nie: Es wird weder aufgezeichnet, gespeichert noch gesendet. Alles funktioniert auch ohne Kamera.',show_plan:'Radar anzeigen',show_camera:'Kamera anzeigen',compass_unavailable:'🧭 Kompass nicht verfügbar — Radar anzeigen',radar_north:'Radar nach Norden — Norden ist oben · Ort wählen',radar_heading:'Das Radar dreht sich mit Ihnen — vorne ist oben · Ort wählen',
      around_me:'📍 In meiner Nähe',key_dates:'📅 Wichtige Daten',buried_people:'★ Hier bestattete Persönlichkeiten',did_you_know:'Schon gewusst?',place_site:'🌐 Website des Ortes',official_page:'Offizielle oder institutionelle Seite',access_mode:'Anreise',listen:'🔊 Anhören',stop:'⏸️ Stopp',back:'← Zurück',go:'📍 Route',fly_book:'Mit F.L.Y Taxi buchen',fly_yvelines:'Für dieses Ziel im Département Yvelines (78) · Dienst des Herausgebers',fly_qr:'Kontakt-QR von F.L.Y Taxi anzeigen',fly_contact:'Kontakt F.L.Y Taxi',fly_scan:'Mit einem anderen Telefon scannen, um den Kontakt direkt zu speichern.',call:'☎ Anrufen',add_contact:'＋ Kontakt hinzufügen',book_online:'Online buchen ↗',
      privacy_title:'Datenschutz, ohne Konto oder Werbung',privacy_body:'Paris Invisible enthält kein Werbe-SDK und keine Reichweitenanalyse. Die Kamera zeichnet keine Bilder auf, und die App speichert Ihren Standort nicht auf einem Server.',external_title:'Externe Dienste',external_body:'Die Karte lädt OpenStreetMap-Kacheln nur beim Öffnen. Routen öffnen Google Maps. Offizielle Seiten öffnen sich erst nach Ihrem Tippen. F.L.Y Taxi erscheint nur bei Zielen im Département Yvelines (78).',access_title:'Zugang und Kauf',access_body:'Der kostenlose Download enthält 5 Geschichten. Ein optionaler Einmalkauf für 4,99 € öffnet alle 44 Orte. Kein Abo und keine Werbung.',privacy_link:'Datenschutz',sources_link:'Quellen & Danksagungen',close:'Schließen',
      my_access:'Vollversion',store_intro:'Die App ist mit 5 Geschichten und ohne Werbung kostenlos. Ein Kauf schaltet alle 44 Orte frei.',base_title:'5 kostenlose Geschichten',base_detail:'Eiffelturm, Notre-Dame, Amélie, das kleinste Haus von Paris und Schloss Monte-Cristo.',paris_pack:'Paris komplett',paris_detail:'Alle 44 Orte, Geschichten, Zeitangaben, Anekdoten und Audios in einer dauerhaften Vollversion.',discover:'Freischalten',connecting_store:'Verbindung zum Store…',restore:'Kauf wiederherstellen',store_note:'Einmalkauf · Kein Abo · Zahlung über Apple oder Google',acquired:'✓ Vollversion',acquired_extension:'✓ Vollversion gekauft',wait:'Bitte warten…',unlock_price:'Alles freischalten',store_unavailable:'Store vorübergehend nicht verfügbar',native_only:'In der iOS- und Android-App verfügbar',pending:'Kauf wartet auf Store-Bestätigung. Bis dahin bleibt der Zugang gesperrt.',pack_paris_badge:'Vollversion',pack_parks_badge:'Vollversion',locked_paris:'Mit der Vollversion verfügbar.',locked_parks:'Mit der Vollversion verfügbar.',visited:'✓ entdeckt',locked_label:'gesperrter Inhalt, Vollversion öffnen',suggested:'empfohlen',
      all:'Alle',parks_filter:'🎢 Parks',monuments_filter:'🏛️ Monumente',cinema_filter:'🎬 Kino',history_filter:'👑 Geschichte',hidden_filter:'🕵️ Geheimtipps',artists_filter:'🎨 Künstler',location_denied_toast:'Standort abgelehnt — simulierte Position im Zentrum von Paris',camera_unsupported:'Kamera wird auf diesem Gerät nicht unterstützt',camera_unavailable:'Kamera nicht verfügbar — Sie können ohne sie fortfahren',map_unavailable:'Karte nicht verfügbar — die anderen Modi funktionieren weiter',audio_unavailable:'Audio ist auf diesem Gerät nicht verfügbar',audio_error:'Audiofehler',restored:'Käufe wiederhergestellt und geprüft',restore_failed:'Käufe können derzeit nicht wiederhergestellt werden',purchase_pending:'Kauf wartet auf Bestätigung',unlocked:'Paket freigeschaltet',purchase_failed:'Kauf nicht abgeschlossen — keine Belastung in der App',content_failed:'Gekaufter Inhalt kann nicht gelesen werden: App online neu öffnen',all_discovered:'🏅 Alle zugänglichen Geschichten wurden entdeckt!',you:'Sie',map_fallback:'🗺️ Karte nicht verfügbar. Liste, Radar und Routen funktionieren weiter.',discover_action:'Öffnen',centered:'Auf Ihren Standort zentriert',simulated_position:'Simulierter Standort (Zentrum von Paris)'
    }),
    it: Object.freeze({
      tagline:'La città che ti parla',start:'Esplora Parigi',included_note:'5 storie varie gratuite. Un acquisto apre tutti i 44 luoghi. Senza pubblicità, account o analisi. La fotocamera resta una tua scelta.',privacy_summary:'Privacy',privacy_splash:'Posizione e orientamento non vengono memorizzati. Le immagini della fotocamera non sono registrate né trasmesse.',creation:'Una creazione di',directions_approx:'Indicazioni approssimative',around:'🔭 Intorno',map:'🗺️ Mappa',list:'📜 Elenco',location_loading:'Localizzazione…',precise_location:'Posizione precisa',approx_location:'Posizione appross.',gps_denied:'GPS negato · simulato',gps_unavailable:'GPS non disponibile · simulato',explore_mode:'Modalità esplorazione',explore_text:'Attiva la fotocamera per l’esperienza AR. Le frecce direzionali restano sempre disponibili.',enable_camera:'Attiva la fotocamera',without_camera:'Continua senza fotocamera',camera_privacy:'🔒 Il flusso della fotocamera non lascia mai il telefono: nessuna immagine viene registrata, salvata o inviata. Tutto funziona anche senza fotocamera.',show_plan:'Mostra radar',show_camera:'Mostra fotocamera',compass_unavailable:'🧭 Bussola non disponibile — mostra radar',radar_north:'Radar orientato a nord — il nord è in alto · Scegli un luogo',radar_heading:'Il radar ruota con te — davanti è in alto · Scegli un luogo',
      around_me:'📍 Intorno a me',key_dates:'📅 Date chiave',buried_people:'★ Personalità sepolte qui',did_you_know:'Lo sapevi?',place_site:'🌐 Sito del luogo',official_page:'Pagina ufficiale o istituzionale',access_mode:'Come arrivare',listen:'🔊 Ascolta',stop:'⏸️ Stop',back:'← Indietro',go:'📍 Indicazioni',fly_book:'Prenota con F.L.Y Taxi',fly_yvelines:'Per questa destinazione nelle Yvelines (78) · Servizio dell’editore',fly_qr:'Mostra il QR del contatto F.L.Y Taxi',fly_contact:'Contatto F.L.Y Taxi',fly_scan:'Scansiona con un altro telefono per salvare direttamente il contatto.',call:'☎ Chiama',add_contact:'＋ Aggiungi contatto',book_online:'Prenota online ↗',privacy_title:'Privacy, senza account né pubblicità',privacy_body:'Paris Invisible non integra SDK pubblicitari né strumenti di analisi del pubblico. La fotocamera non registra immagini e l’app non salva la posizione su un server.',external_title:'Servizi esterni',external_body:'La mappa carica le tessere OpenStreetMap solo quando viene aperta. Gli itinerari aprono Google Maps. Le pagine ufficiali si aprono solo dopo un tocco. F.L.Y Taxi appare solo per destinazioni nelle Yvelines (78).',access_title:'Accesso e acquisto',access_body:'Il download gratuito include 5 storie. Un acquisto opzionale una tantum da 4,99 € apre tutti i 44 luoghi. Nessun abbonamento né pubblicità.',privacy_link:'Privacy',sources_link:'Fonti e crediti',close:'Chiudi',
      my_access:'Versione completa',store_intro:'L’app è gratuita con 5 storie e senza pubblicità. Un solo acquisto sblocca tutti i 44 luoghi.',base_title:'5 storie gratuite',base_detail:'Torre Eiffel, Notre-Dame, Amélie, la casa più piccola di Parigi e il castello di Montecristo.',paris_pack:'Parigi completa',paris_detail:'Tutti i 44 luoghi, racconti, date, aneddoti e audio in una versione completa permanente.',discover:'Sblocca',connecting_store:'Connessione allo Store…',restore:'Ripristina il mio acquisto',store_note:'Acquisto unico · Nessun abbonamento · Pagamento gestito da Apple o Google',acquired:'✓ Versione completa',acquired_extension:'✓ Versione completa acquistata',wait:'Attendi…',unlock_price:'Sblocca tutto',store_unavailable:'Store temporaneamente non disponibile',native_only:'Disponibile nell’app iOS e Android',pending:'Acquisto in attesa della conferma dello Store. L’accesso resta bloccato fino alla conferma.',pack_paris_badge:'Versione completa',pack_parks_badge:'Versione completa',locked_paris:'Disponibile con la versione completa.',locked_parks:'Disponibile con la versione completa.',visited:'✓ scoperto',locked_label:'contenuto bloccato, apri Versione completa',suggested:'consigliato',
      all:'Tutto',parks_filter:'🎢 Parchi',monuments_filter:'🏛️ Monumenti',cinema_filter:'🎬 Cinema',history_filter:'👑 Storia',hidden_filter:'🕵️ Curiosità',artists_filter:'🎨 Artisti',location_denied_toast:'Posizione negata — posizione simulata nel centro di Parigi',camera_unsupported:'Fotocamera non supportata su questo dispositivo',camera_unavailable:'Fotocamera non disponibile — puoi continuare senza',map_unavailable:'Mappa non disponibile — le altre modalità restano attive',audio_unavailable:'Audio non disponibile su questo dispositivo',audio_error:'Errore audio',restored:'Acquisti ripristinati e verificati',restore_failed:'Impossibile ripristinare gli acquisti ora',purchase_pending:'Acquisto in attesa di conferma',unlocked:'Pacchetto sbloccato',purchase_failed:'Acquisto non completato — nessun addebito nell’app',content_failed:'Contenuto acquistato illeggibile: riapri l’app online',all_discovered:'🏅 Hai scoperto tutte le storie accessibili!',you:'Tu',map_fallback:'🗺️ Mappa non disponibile. Elenco, radar e itinerari funzionano ancora.',discover_action:'Apri',centered:'Centrato sulla tua posizione',simulated_position:'Posizione simulata (centro di Parigi)'
    }),
    ja: Object.freeze({
      tagline:'街があなたに語りかける',start:'パリを探索',included_note:'多彩な5話を無料提供。1回の購入で全44か所を開放します。広告、アカウント、解析ツールはありません。カメラの使用はいつでも選べます。',privacy_summary:'プライバシー',privacy_splash:'位置と向きは保存されません。カメラ画像は記録・送信されません。',creation:'制作',directions_approx:'方向は目安です',around:'🔭 周辺',map:'🗺️ 地図',list:'📜 一覧',location_loading:'位置を確認中…',precise_location:'正確な位置',approx_location:'おおよその位置',gps_denied:'GPS拒否・シミュレーション',gps_unavailable:'GPS利用不可・シミュレーション',explore_mode:'探索モード',explore_text:'AR体験にはカメラを有効にしてください。方向矢印は常に使えます。',enable_camera:'カメラを有効にする',without_camera:'カメラなしで続ける',camera_privacy:'🔒 カメラ映像は端末の外へ出ません。画像は記録、保存、送信されず、カメラなしでもすべて利用できます。',show_plan:'レーダーを表示',show_camera:'カメラを表示',compass_unavailable:'🧭 コンパスを利用できません—レーダーを表示',radar_north:'北向きレーダー—上が北です・場所を選択',radar_heading:'レーダーは向きに合わせて回転—上が前方です・場所を選択',
      around_me:'📍 現在地周辺',key_dates:'📅 主な年代',buried_people:'★ ここに眠る著名人',did_you_know:'ご存じですか？',place_site:'🌐 公式サイト',official_page:'公式・公的ページ',access_mode:'アクセス',listen:'🔊 聴く',stop:'⏸️ 停止',back:'← 戻る',go:'📍 経路',fly_book:'F.L.Y Taxiを予約',fly_yvelines:'イヴリーヌ県（78）の目的地向け・発行者提供サービス',fly_qr:'F.L.Y Taxi連絡先QRを表示',fly_contact:'F.L.Y Taxi連絡先',fly_scan:'別の端末で読み取り、連絡先を直接保存できます。',call:'☎ 電話',add_contact:'＋ 連絡先を追加',book_online:'オンライン予約 ↗',privacy_title:'アカウント・広告なしのプライバシー',privacy_body:'Paris Invisibleには広告SDKや利用状況解析ツールがありません。カメラは画像を記録せず、アプリは位置情報をサーバーに保存しません。',external_title:'外部サービス',external_body:'地図を開いた時だけOpenStreetMapタイルを読み込みます。経路はGoogle Mapsを開き、公式ページはタップ後に開きます。F.L.Y Taxiはイヴリーヌ県（78）の目的地だけに表示されます。',access_title:'アクセスと購入',access_body:'無料ダウンロードには5話が含まれます。任意の4.99ユーロ買い切りで全44か所を開放します。定期購入も広告もありません。',privacy_link:'プライバシー',sources_link:'出典・クレジット',close:'閉じる',
      my_access:'完全版',store_intro:'アプリは5話付きで無料、広告はありません。1回の購入で全44か所を解放します。',base_title:'無料の5話',base_detail:'エッフェル塔、ノートルダム、『アメリ』、パリで最も小さな家、モンテ・クリスト城。',paris_pack:'パリ完全版',paris_detail:'44か所すべての物語、年代、逸話、音声を買い切りの完全版で楽しめます。',discover:'ロック解除',connecting_store:'ストアに接続中…',restore:'購入を復元',store_note:'買い切り・定期購入なし・支払いはAppleまたはGoogleが処理',acquired:'✓ 完全版',acquired_extension:'✓ 完全版購入済み',wait:'お待ちください…',unlock_price:'すべて解除',store_unavailable:'ストアを一時的に利用できません',native_only:'iOS・Androidアプリで利用できます',pending:'ストアの確認待ちです。確認されるまでアクセスは解除されません。',pack_paris_badge:'完全版',pack_parks_badge:'完全版',locked_paris:'完全版で利用できます。',locked_parks:'完全版で利用できます。',visited:'✓ 発見済み',locked_label:'ロック中。完全版を開く',suggested:'おすすめ',
      all:'すべて',parks_filter:'🎢 パーク',monuments_filter:'🏛️ 名所',cinema_filter:'🎬 映画',history_filter:'👑 歴史',hidden_filter:'🕵️ 秘境',artists_filter:'🎨 芸術家',location_denied_toast:'位置情報が拒否されました—パリ中心部の模擬位置を使用',camera_unsupported:'この端末はカメラ機能に対応していません',camera_unavailable:'カメラを利用できません—なしで続けられます',map_unavailable:'地図を利用できません—他のモードは使用できます',audio_unavailable:'この端末では音声を利用できません',audio_error:'音声エラー',restored:'購入を復元して確認しました',restore_failed:'現在、購入を復元できません',purchase_pending:'購入確認待ち',unlocked:'パックを解除しました',purchase_failed:'購入は完了していません—アプリ内請求なし',content_failed:'購入済みコンテンツを読めません。オンラインでアプリを再起動してください',all_discovered:'🏅 利用可能なすべての物語を発見しました！',you:'現在地',map_fallback:'🗺️ 地図を利用できません。一覧、レーダー、経路は使えます。',discover_action:'開く',centered:'現在地を中心に表示',simulated_position:'模擬位置（パリ中心部）'
    })
  });
  root.PIExtraI18N = locales;
  if (typeof module !== 'undefined' && module.exports) module.exports = locales;
})(typeof globalThis !== 'undefined' ? globalThis : this);
